services:
  db:
    image: mysql:8.0
    platform: linux/x86_64
    command: --default-authentication-plugin=mysql_native_password --sql_mode=""
    environment:
      - MYSQL_ROOT_PASSWORD=root

  web: &web
    platform: linux/x86_64
    stdin_open: true
    tty: true
    build:
      context: ./
      dockerfile: Dockerfile.dev
    command: sh /docker-entrypoint.sh
    ports:
      - "3000:8080"
    env_file:
      - .env
    environment:
      RAILS_ENV: development
      HISTFILE: /usr/src/app/log/.bash_history
      BUNDLER_VERSION: '2.4.7'
      DATABASE_PASSWORD: root
      DATABASE_HOST: db
      DATABASE_PORT: 3306
    depends_on:
      - db
    volumes:
      - .:/workspace
      - bundle:/workspace/vendor/bundle

volumes:
  bundle:
